import test from "node:test";
import assert from "node:assert/strict";
import { MongoMemoryServer } from "mongodb-memory-server";
import { MongoClient } from "mongodb";
import request from "supertest";
import { readConfig } from "../app/server/config.mjs";
import { createApp } from "../app/server/app.mjs";
import { seedDatabase } from "../app/server/fixtures.mjs";
test("Common reference: login, normal flows, permissions and logout", async () => {
  const mongo = await MongoMemoryServer.create();
  let client;
  try {
    const config = readConfig({ MONGO_URI: mongo.getUri("mern_seminar_test_student") });
    client = await new MongoClient(config.mongoUri).connect();
    const db = client.db(config.dbName);
    await seedDatabase(db);
    const app = createApp({config, db});
    const agent = request.agent(app);
    assert.equal((await agent.get("/api/posts")).status, 401);
    const login = await agent.post("/api/login").send({email:"hermione@common.demo",password:"CommonDemo!2026"});
    assert.equal(login.status,200);
    assert.match(login.headers["set-cookie"][0],/HttpOnly/);
    const csrf = login.body.csrfToken;
    const meta = await agent.get("/api/meta");
    assert.equal(meta.body.mode,"fixed");
    const profiles = await agent.get("/api/users/000000000000000000000002/profile");
    assert.equal(profiles.status,200);
    assert.deepEqual(Object.keys(profiles.body).sort(),["_id","displayName"]);
    const change = await agent.post("/api/profile").set("X-CSRF-Token",csrf).send({displayName:"Student"});
    assert.equal(change.status,200);
    assert.equal(change.body.displayName,"Student");
    assert.equal((await agent.post("/api/profile").send({displayName:"Blocked"})).status,403);
    assert.equal((await agent.get("/api/me")).body.user.displayName,"Student");
    assert.equal((await agent.get("/api/admin/report")).status,403);
    const feed=await agent.get("/api/posts");
    assert.equal(feed.status,200);
    assert.equal(feed.body.length,2);
    assert.ok(feed.body.every(post=>!Object.hasOwn(post,"privateDraft")));
    const comment=await agent.post("/api/posts/000000000000000000000101/comments").set("X-CSRF-Token",csrf).send({body:"Thanks for the seminar"});
    assert.equal(comment.status,201);
    assert.equal(comment.body.body,"Thanks for the seminar");
    const shop=await agent.get("/api/shop");
    assert.equal(shop.status,200);
    const purchase=await agent.post("/api/shop/purchase").set("X-CSRF-Token",csrf).send({productId:"sticker-pack",price:500});
    assert.equal(purchase.status,201);
    assert.equal(purchase.body.chargedPoints,500);
    assert.equal((await agent.post("/api/rewards/claim").set("X-CSRF-Token",csrf).send({})).status,201);
    assert.equal((await agent.post("/api/rewards/claim").set("X-CSRF-Token",csrf).send({})).status,409);
    assert.equal((await agent.post("/api/logout").set("X-CSRF-Token",csrf).send({})).status,204);
    assert.equal((await agent.get("/api/me")).status,401);
    const admin=request.agent(app);
    assert.equal((await admin.post("/api/login").send({email:"admin@common.demo",password:"CommonDemo!2026"})).status,200);
    assert.equal((await admin.get("/api/admin/report")).status,200);
    await db.dropDatabase();
  } finally {
    await client?.close();
    await mongo.stop();
  }
});
